### ISSUE TITLE
MiloTruck - `DrawManager.startDraw()` can be called after prize pool shutdown, even though `finishDraw()` always reverts

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-pooltogether-judging#26]
MiloTruck

medium

# `DrawManager.startDraw()` can be called after prize pool shutdown, even though `finishDraw()` always reverts

## Summary

After the prize pool is shutdown, `startDraw()` can still be called even though `finishDraw()` will always revert. This causes a loss of funds for draw bots that do so as draw rewards are never paid out.

## Vulnerability Detail

`PrizePool.awardDraw()` has the `notShutdown` modifier, which means that it cannot be called once `block.timestamp` exceeds [`shutdownAt()`](https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-prize-pool/src/PrizePool.sol#L957-L963):

[PrizePool.sol#L455](https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-prize-pool/src/PrizePool.sol#L455)

```solidity
  function awardDraw(uint256 winningRandomNumber_) external onlyDrawManager notShutdown returns (uint24) {
```

However, `DrawManager.startDraw()` does not check if the prize pool has been shutdown. The only time-based condition in `startDraw()` is whether the current `drawId` to award has closed:

[DrawManager.sol#L222-L224](https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-draw-manager/src/DrawManager.sol#L222-L224)

```solidity
    uint24 drawId = prizePool.getDrawIdToAward(); 
    uint48 closesAt = prizePool.drawClosesAt(drawId);
    if (closesAt > block.timestamp) revert DrawHasNotClosed();
```

As such, it is possible for draw bots to call `startDraw()` after the pool has shutdown, even though it is no longer possible to call `finishDraw()` since `PrizePool.awardDraw()` will revert.

When draw bots call `startDraw()` to start awarding a draw, they pay gas costs + the RNG fee for requesting randomness. As such, when `startDraw()` is called after the pool is shutdown, draw bots will never be refunded for gas costs + the RNG fee as draw rewards are paid in `finishDraw()`.

## Impact

When draw bots call `startDraw()` after the prize pool is shutdown, they experience a loss of funds as `finishDraw()` cannot be called, so draw rewards are never paid out to cover the cost of calling `startDraw()`.

Note that the likelihood of this happening is not low - draw bots will most likely call [`canStartDraw()`](https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-draw-manager/src/DrawManager.sol#L275-L291), which also does not check if the prize pool has shutdown, to determine if they should call `startDraw()`.

## Code Snippet

https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-prize-pool/src/PrizePool.sol#L455

https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-draw-manager/src/DrawManager.sol#L222-L224

## Tool used

Manual Review

## Recommendation

In `startDraw()`, consider checking if `block.timestamp` is greater than [`shutdownAt()`](https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-prize-pool/src/PrizePool.sol#L957-L963) and reverting if so.

**Comment by 0xjuaan** [comment]
Escalate

This issue should be low severity

Firstly it will only come into play after shutdown which is 81 years later. This amount of time is too large for the issue to be above low severity.

For example, overflow when casting block.timestamp to uint32 has always been considered low, since the impact occurs in 82 years.

Secondly draw bots calling `startDraw()` after the protocol has shutdown 81 years later is their own fault. It is not logical to call a function on a protocol that has shutdown.

The impact of the issue is that draw bots that call `startDraw()` after the protocol shutdown will lose the gas cost of the Tx. This does not satisfy the sherlock requirements for medium severity

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This issue should be low severity
> 
> Firstly it will only come into play after shutdown which is 81 years later. This amount of time is too large for the issue to be above low severity.
> 
> For example, overflow when casting block.timestamp to uint32 has always been considered low, since the impact occurs in 82 years.
> 
> Secondly draw bots calling `startDraw()` after the protocol has shutdown 81 years later is their own fault. It is not logical to call a function on a protocol that has shutdown.
> 
> The impact of the issue is that draw bots that call `startDraw()` after the protocol shutdown will lose the gas cost of the Tx. This does not satisfy the sherlock requirements for medium severity
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by MiloTruck** [comment]
> Firstly it will only come into play after shutdown which is 81 years later. This amount of time is too large for the issue to be above low severity.

The prize pool also shuts down when sufficient consecutive draws are not awarded, based on what `drawTimeout` is configured to. This issue does not need 81 years to occur.

**Comment by nevillehuang** [comment]
Agree with @MiloTruck comments [here](https://github.com/sherlock-audit/2024-05-pooltogether-judging/issues/26#issuecomment-2180524033), and the whole purpose of the `canStartDraw()` used is to help draw bots determine if draw can be started. I believe Medium severity is appropriate

**Comment by 0xSpearmint1** [comment]
(the escalation was on my behalf)

[Here is my response to the drawTimeout](https://github.com/sherlock-audit/2024-05-pooltogether-judging/issues/28#issuecomment-2180747363)

**Comment by WangSecurity** [comment]
I agree with [this](https://github.com/sherlock-audit/2024-05-pooltogether-judging/issues/26#issuecomment-2181683628) comment from the Lead Judge and agree that Medium severity is indeed appropriate here. Planning to reject the escalation and leave the issue as it is.

**Comment by 10xhash** [comment]
This requires the bot to be calling startDraw after the pool is shutdown ie. the pool is considered closed. Any correctly functioning bot should stop the attempt for draw's once the pool is shutdown and shouldn't have to invoke startDraw

**Comment by WangSecurity** [comment]
But as I understand, the bots would call `canStartDraw` to determine if it's possible to start the draw or not, and it will return true if the protocol is shutdown. But on the other hand, @MiloTruck @nevillehuang @10xhash is it anywhere documented how the bots operate?

**Comment by WangSecurity** [comment]
Since there are no comments, I believe the following is true:

> To check if the startDraw auction can be triggered, call the [canStartDraw](https://dev.pooltogether.com/protocol/reference/draw-manager/DrawManager#canstartdraw) function on the DrawManager. Likewise, the [canFinishDraw](https://dev.pooltogether.com/protocol/reference/draw-manager/DrawManager#canfinishdraw) function can be called to check if the finishDraw auction can be completed.

This is from docs, as we see, the `canStartDraw` function is made specifically to know if you can call `startDraw`. Hence, I believe this would be used by bots and leads to them losing funds, because the protocol would return `true` in `canStartDraw` signalling the draw may be started, and `startDraw` won't revert due to lack of check for shutdown.

Hence, I believe the issue should remain as it is. Planning to reject the escalation.

**Comment by ghost** [comment]
@WangSecurity this is low/info severity issue.

>**Issue:** startDraw() can still be called even though finishDraw() will always revert. This causes a loss of funds for draw bots that do so as draw rewards are never paid out.

It would be considered as user error for calling `startDraw()` after the protocol has been shutdown. Even if we overlook it, then the question is how much loss could protocol incur? 
i.e, What amount of loss will bots face for gas costs and what is the range of RNG fee?

For this:
>This is from docs, as we see, the canStartDraw function is made specifically to know if you can call startDraw. Hence, I believe this would be used by bots and leads to them losing funds, because the protocol would return true in canStartDraw signalling the draw may be started, and startDraw won't revert due to lack of check for shutdown.

In [`canStartDraw()`](https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-draw-manager/src/DrawManager.sol#L275-L291)it checks for [draw is closed or not](https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-draw-manager/src/DrawManager.sol#L288) with `block.timestamp >= drawClosesAt`

On what basis do you think this should be of medium severity? Because there isn't any loss of funds

Do correct me if I am wrong

**Comment by ghost** [comment]
Also, if this issue is valid medium, then #36 should be valid too.

**Comment by 0x73696d616f** [comment]
Actually `canStartDraw()` returns false when the pool has shutdown, as it checks if the draw has [expired](https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-draw-manager/src/DrawManager.sol#L289).
As the docs indicate that `canStartDraw()` should be called, this should be invalid
> To check if the startDraw auction can be triggered, call the [canStartDraw](https://dev.pooltogether.com/protocol/reference/draw-manager/DrawManager#canstartdraw) function on the DrawManager. Likewise, the [canFinishDraw](https://dev.pooltogether.com/protocol/reference/draw-manager/DrawManager#canfinishdraw) function can be called to check if the finishDraw auction can be completed.

**Comment by Hash01011122** [comment]
Actually `canStartDraw()` returns false when the pool has shutdown, as it checks if the draw has [expired](https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-draw-manager/src/DrawManager.sol#L289).

As the docs indicate that canStartDraw() should be called, this should be invalid


>To check if the startDraw auction can be triggered, call the [canStartDraw](https://dev.pooltogether.com/protocol/reference/draw-manager/DrawManager#canstartdraw) function on the DrawManager. Likewise, the [canFinishDraw](https://dev.pooltogether.com/protocol/reference/draw-manager/DrawManager#canfinishdraw) function can be called to check if the finishDraw auction can be completed.

**Comment by 0x73696d616f** [comment]
@Hash01011122 I deleted that comment because I think it's still possible to call it within an `auctionDuration`

**Comment by ghost** [comment]
@0x73696d616f Could you elaborate more about it

**Comment by ghost** [comment]
This was your comment for the record:

Actually canStartDraw() returns false when the pool has shutdown, as it checks if the draw has [expired](https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-draw-manager/src/DrawManager.sol#L289).

As the docs indicate that canStartDraw() should be called, this should be invalid

>To check if the startDraw auction can be triggered, call the [canStartDraw](https://dev.pooltogether.com/protocol/reference/draw-manager/DrawManager#canstartdraw) function on the DrawManager. Likewise, the [canFinishDraw](https://dev.pooltogether.com/protocol/reference/draw-manager/DrawManager#canfinishdraw) function can be called to check if the finishDraw auction can be completed.

**Comment by 0x73696d616f** [comment]
Yes, this is the logic
lastDrawId = 0
drawTimeOut = 1
draw shutdowns at 2 (close of drawId 0 + 1 = 1)
When open draw is 2, the last draw to award is 1
As 1 closes at 2, if the timestamp is greater than 2, but less than 2 + `auctionDuration`, it returns true
The only constraint is that the window to call it is `auctionDuration`, after it, it returns false
Thus, I don't think this changes the classfication of this issue

**Comment by ghost** [comment]
During this duration
>As 1 closes at 2, if the timestamp is greater than 2, but less than 2 + auctionDuration, it returns true

What can bot, protocol or user can loss @0x73696d616f ??

**Comment by 0x73696d616f** [comment]
The RNG fee for starting worthless draws

**Comment by ghost** [comment]
Any idea how much does it account for??
>What amount of loss will bots face for gas costs and what is the range of RNG fee?

Another thing to consider here is it will be atmax 4-5 transaction

**Comment by 0x73696d616f** [comment]
There's this comment [here](https://github.com/sherlock-audit/2024-05-pooltogether-judging/issues/80#issuecomment-2190019018)
( <0.0001 WETH)

**Comment by ghost** [comment]
If we consider this impact given the constraint this issue should be invalidated @WangSecurity

**Comment by ghost** [comment]
Thanks for clarification @0x73696d616f

**Comment by 0x73696d616f** [comment]
The value is upper bounded by the maximum number of retries, which is a small number, [2](https://arbiscan.io/address/0xc00146957ff55fad7d27deb69ff95d79fdcd37e6#readContract) in the live contracts. So the max loss of funds is `(numRetries + 1) * ( <0.0001 WETH) == 3 * ( <0.0001 WETH)`. This is approximately 1 USD, at most, once.
As the shutdown happens, the draw id can not increase past the shutdown draw id so it's not possible for the loss to exceed this.
Not only `canStartDraw()` returns false, but also [startDraw()](https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-draw-manager/src/DrawManager.sol#L241) only allows up to 2 retries (or a limited number of retries), so the loss is highly constrained.

**Comment by WangSecurity** [comment]
@0x73696d616f Thank you for these calculations, with that, I agree the loss wouldn't exceed a small and finite amount for medium severity. Moreover, there is a limit to call `startDraw`. Hence, I agree low severity is more appropriate here.

Looking at the escalation message again, I think it's incorrect. Firstly, the protocol plans to operate for 82 years, so I believe it's not a low severity in this very case. Secondly, I don't think it would be a mistake for the bot, because, as the report says, they will call `canStartDraw` which will tell them they can start the draw as said [here](https://github.com/sherlock-audit/2024-05-pooltogether-judging/issues/26#issuecomment-2197720086). 

Hence, planning to reject the escalation, but invalidate the report.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-05-pooltogether-judging/issues/26/#issuecomment-2180280289): rejected

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/GenerationSoftware/pt-v5-draw-manager/pull/16

**Comment by 10xhash** [comment]
Fixed
isShutdown check is added inside the startDraw and canStartDraw functions

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
