### ISSUE TITLE
0xSpearmint1 - An attacker can take advantage of a yield vault that made a loss, at the expense of all other users

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-pooltogether-judging#44]
0xSpearmint1

medium

# An attacker can take advantage of a yield vault that made a loss, at the expense of all other users

## Summary
An attacker can take advantage of a yield vault that made a loss, at the expense of all other users.

## Vulnerability Detail

The protocol intends to "socialize" losses to all users when a YieldVault experiences a significant loss. 

The protocol does this in the `previewWithdraw()` function when a user calls `withdraw()`

`withdraw()` ==> `previewWithdraw()` ==> `_convertToShares`

```solidity
function _convertToShares(
        uint256 _assets,
        uint256 _totalAssets,
        uint256 _totalDebt,
        Math.Rounding _rounding
    ) internal pure returns (uint256) {
        if (_totalAssets >= _totalDebt) {
            return _assets;
        } else {
            // If the vault controls less assets than what has been deposited a share will be worth a
            // proportional amount of the total assets. This can happen due to fees, slippage, or loss
            // of funds in the underlying yield vault.
            return _assets.mulDiv(_totalDebt, _totalAssets, _rounding);
        }
    }
```

If the YieldVault experiences a significant loss then `totalAssets < _totalDebt`, therefore the `else` block will go through to socialize the loss.

The vulnerability is that an attacker can frontrun a YieldVault entering a loss state by withdrawing from the PrizeVault, this withdraw will have `totalAssets > _totalDebt` therefore the `if` block will go through, the attacker will get more assets than they should since the `if` block will go through for them.

## Impact
Attacker unfairly avoids the protocol's intended loss socialization

Attacker has exacerbated other user's losses

## Code Snippet
https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-vault/src/PrizeVault.sol#L886-L900

## Tool used

Manual Review

## Recommendation
This is not easy to mitigate, this should be a risk communicated to users.

**Comment by 0xSpearmint1** [comment]
This is a valid medium severity issue

The lead judge's comment does not invalidate the issue

The **attack path** invlolves interacting with `prizeVault` NOT THE `yieldVault`

The **impact** will be an exarcebated loss for all other depositors in the `prizeVault` to benefit the attacker

**Comment by 0xjuaan** [comment]
Escalate
On behalf of @0xspearmint1

**Comment by sherlock-admin3** [comment]
> Escalate
> On behalf of @0xspearmint1

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
I don't see where the issue is, if the attacker withdraws before the YieldVault is in debt, then they should go through the if statement. It's how it should work, the vulnerability would be going through the if statement when the YieldVault is in the loss, but here, the attacker does so before. Hence, if I'm not missing anything, this works as intended.

Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-05-pooltogether-judging/issues/44/#issuecomment-2180247080): rejected
