### ISSUE TITLE
0xSpearmint1 - YieldVaults with fee on deposit are incompatible with the protocol

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-pooltogether-judging#45]
0xSpearmint1

medium

# YieldVaults with fee on deposit are incompatible with the protocol

## Summary
YieldVaults with fee on deposit are incompatible with the protocol 

## Vulnerability Detail
The vulnerability lies in the following check in `_depositAndMint()`

```solidity
function _depositAndMint(address _caller, address _receiver, uint256 _assets, uint256 _shares) internal {
    ...
    ...
    if (totalPreciseAssets() < _totalDebtBeforeMint + _shares) {
            revert LossyDeposit(totalPreciseAssets(), _totalDebtBeforeMint + _shares);
    ...
    ... 
```

If the YieldVault has a fee on deposit then `totalPreciseAssets <  _totalDebtBeforeMint + _shares`, therefore the check will revert

## Impact
The protocol cannot integrate with a lot of vaults.

Any user that created a PrizeVault with a fee on deposit YieldVault will waste a lot of money and time deploying the contract.

## Code Snippet
https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-vault/src/PrizeVault.sol#L991-L992

## Tool used

Manual Review

## Recommendation
Fixing this is up to the protocol. I would recommend adding this as a known risk

**Comment by 0xSpearmint1** [comment]
This is a valid medium severity issue

The issue is regarding fee on deposit vaults NOT fee on transfer tokens like the lead judge stated

**Comment by 0xjuaan** [comment]
Escalate
On behalf of @0xspearmint1

**Comment by sherlock-admin3** [comment]
> Escalate
> On behalf of @0xspearmint1

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by trmid** [comment]
This is documented in the prize vault contract natspec:
https://github.com/sherlock-audit/2024-05-pooltogether/blob/1aa1b8c028b659585e4c7a6b9b652fb075f86db3/pt-v5-vault/src/PrizeVault.sol#L66

as well as the reference docs (same as the natspec):
https://dev.pooltogether.com/protocol/reference/prize-vault/PrizeVault

**Comment by nevillehuang** [comment]
In addition to sponsor comments, this was publicly noted [here](https://discord.com/channels/812037309376495636/1240709589176025149/1246177365990572096), and in which:

> The Sherlock Judge can use public statements up until 24h before the contest ends to override the language in the chosen source of truth.

Escalation should be rejected

**Comment by 0xSpearmint1** [comment]
Agreed. I did not see those statements.

The judging comments was what triggered the escalation.

**Comment by WangSecurity** [comment]
Since the escalator agrees, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-05-pooltogether-judging/issues/45/#issuecomment-2180247894): rejected
